export const toitsuNavMapConsts = {
  '/inm/inmate/view': '/inm/inmate/list',
  '/inm/inmate/folder': '/inm/inmate/list',
  '/inm/inmate/oldlist': '/inm/inmate/list',
  '/inm/inmate/oldview': '/inm/inmate/list',
  '/inm/inmate/photolist': '/inm/inmate/list',
  '/inm/inmate/laborcatalog': '/inm/inmate/list',
  '/inm/discipline/view': '/inm/discipline/list',
  '/inm/disciplinereport/view': '/inm/disciplinereport/list',
  '/inm/disciplinecouncil/view': '/inm/disciplinecouncil/list',
  '/inm/appeal/view': '/inm/appeal/list',
  '/inm/transport/view': '/inm/transport/list',
  '/inm/vacation/view': '/inm/vacation/list',
  '/inm/vacationapplication/view': '/inm/vacationapplication/list',
  '/inm/vacationapplication/motion/view': '/inm/vacationapplication/motion/list',
  '/inm/vacationcouncil/view': '/inm/vacationcouncil/list',
  '/inm/courtsummons/view': '/inm/courtsummons/list',
  '/inm/transfer/view': '/inm/transfer/list',
  '/inm/inmatelabor/view': '/inm/inmatelabor/list',
  '/inm/inmatelaborapplication/view': '/inm/inmatelaborapplication/list',
  '/inm/inmatelaborapplication/masscreate': '/inm/inmatelaborapplication/list',
  '/inm/placementprotocol/view': '/inm/placementprotocol/list',
  '/inm/laborday/view': '/inm/laborday/list',
  '/inm/laborprotocol/view': '/inm/laborprotocol/list',
  '/inm/visit/view': '/inm/visit/list',
  '/inm/visitor/view': '/inm/visitor/list',
  '/inm/eventrecord/view': '/inm/eventrecord/list',
  '/inm/area/view': '/inm/area/list',
  '/inm/postletter/view': '/inm/postletter/list',
  '/inm/gatemovement/view': '/inm/gatemovement/list',
  '/inm/gatemovement/masscreate': '/inm/gatemovement/list',
  '/inm/gatemovement/massclose': '/inm/gatemovement/list',
  '/inm/vehicle/view': '/inm/vehicle/list',
  '/inm/visitprogram/view': '/inm/visitprogram/list',
  '/inm/doctorsession/psychologist/view': '/inm/doctorsession/psychologist/list',
  '/inm/doctorsession/socialworker/view': '/inm/doctorsession/socialworker/list',
  '/inm/doctorsession/sociologist/view': '/inm/doctorsession/sociologist/list',
  '/inm/doctorsession/criminologist/view': '/inm/doctorsession/criminologist/list',
  '/inm/hearingapplication/view': '/inm/hearingapplication/list',
  '/inm/educationneed/view': '/inm/educationneed/list',
  '/inm/visitapplication/view': '/inm/visitapplication/list',
  '/inm/program/view': '/inm/program/list',
  '/inm/programapplication/view': '/inm/programapplication/list',
  '/inm/programprotocol/view': '/inm/programprotocol/list',
  '/inm/program/conduct/view': '/inm/program/conduct/list',

  '/med/hearingapplication/view': '/med/hearingapplication/list',
  '/med/prescription/view': '/med/prescription/list',
  '/med/medicalfolder/view': '/med/medicalfolder/list',
  '/med/doctorsession/doctor/view': '/med/doctorsession/doctor/list',
  '/med/disease/view': '/med/disease/list',
  '/med/examination/view': '/med/examination/list',
  '/med/vaccination/view': '/med/vaccination/list',
  '/med/bloodsampling/view': '/med/bloodsampling/list',
  '/med/treatment/view': '/med/treatment/list',
  '/med/hearing/view': '/med/hearing/list',
  '/med/medicine/view': '/med/medicine/list',
  '/med/referral/view': '/med/referral/list',
  '/med/shift/view': '/med/shift/list',
  '/med/diseasetype/view': '/med/diseasetype/list',
  '/med/vaccine/view': '/med/vaccine/list',
  '/med/hearingtype/view': '/med/hearingtype/list',
  '/med/examinationtype/view': '/med/examinationtype/list',
  
  '/sa/classification/view' : '/sa/classification/list',
  '/sa/doctor/view': '/sa/doctor/list',
  '/sa/country/view': '/sa/country/list',
  '/sa/courthouse/view': '/sa/courthouse/list',
  '/sa/vacationtype/view' : '/sa/vacationtype/list',
  '/sa/visittype/view' : '/sa/visittype/list',
  '/sa/areatype/view' : '/sa/areatype/list',
  '/sa/gatemovementtype/view' : '/sa/gatemovementtype/list',
  '/sa/sessiontype/view' : '/sa/sessiontype/list',
  '/sa/programtype/view' : '/sa/programtype/list',
  '/sa/policedepartment/view' : '/sa/policedepartment/list',
  '/sa/hospital/view': '/sa/hospital/list',
  '/sa/director/view': '/sa/director/list',
  '/sa/detentioncenter/view': '/sa/detentioncenter/list',
  '/sa/template/view': '/sa/template/list',
  '/sa/notificationtype/view': '/sa/notificationtype/list',
  '/sa/notification/view': '/sa/notification/list'
};
