export const inmateConsts = {
  indexUrl: '/inm/inmates/index',
  getUrl: '/inm/inmates/get',
  saveUrl: '/inm/inmates/save',
  deleteUrl: '/inm/inmates/delete',
  getFolderUrl: '/inm/inmates/getfolder',
  saveFolderUrl: '/inm/inmates/savefolder',
  closeFolderUrl: '/inm/inmates/closefolder',
  reopenFolderUrl: '/inm/inmates/reopenfolder',
  oldIndexUrl: '/inm/inmates/oldindex',
  getOldUrl: '/inm/inmates/getold',
  acceptOldUrl: '/inm/inmates/acceptold',
  getActiveUrl: '/inm/inmates/getactive',
  activeIndexUrl: '/inm/inmates/activeindex',
  getLastRecordUrl: '/inm/inmates/getlastrecord',
  lastRecordIndexUrl: '/inm/inmates/lastrecordindex',
  getMiniUrl: '/inm/inmates/getmini',
  getEducationDetailsUrl: '/inm/inmates/geteducationdetails',
  saveMedDetailsUrl: '/inm/inmates/savemeddetails'
};
